name: Trigger auto deployment for serene-env

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'test/**'
    - '.github/workflows/serene-env-AutoDeployTrigger-41b93753-0d77-48fb-8263-c6b786fa71d1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: serene.azurecr.io
          username: ${{ secrets.SERENEENV_REGISTRY_USERNAME }}
          password: ${{ secrets.SERENEENV_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: serene.azurecr.io/mvc:${{ github.sha }}
          file: ./test/Dockerfile
          context: ./test/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERENEENV_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n serene-env -g serene-env --server serene.azurecr.io --username  ${{ secrets.SERENEENV_REGISTRY_USERNAME }} --password ${{ secrets.SERENEENV_REGISTRY_PASSWORD }}
            az containerapp update -n serene-env -g serene-env --image serene.azurecr.io/mvc:${{ github.sha }}
